version: '3.8'
services:
  nestjs-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nestjs-db
    networks:
      - freecodecamp
networks:
  freecodecamp: